# Site wide configuration

description       : Türkçe Tercümesi
title             : Kur'an-ı Kerim
logo              : muhur2.png
search            : false
baseurl           : "" # the subpath of your site, e.g. /blog/
url               : https://jeruselam.github.io
author:
  name            : "Kur'an-ı Kerim - Türkçe Tercümesi"
  url             : https://jeruselam.github.io
  email           : jeruselam@yandex.com
  bio             : "Just another tattooed, time traveling designer."
  picture         : "/images/apple-icon-120x120.png"

# Location

address           : Türkiye
locale            : tr_TR
languages         : ['en', 'tr']
language_default  : 'tr'

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false


# Jekyll configuration

enforce_ssl       : jeruselam.github.io
encoding          : utf-8
safe              : bool
timezone          : Europe/Istanbul
permalink         : /:categories/:title/
markdown          : kramdown
highlighter       : rouge
sass:
  sass_dir        : _sass
  style           : compressed
plugins_dir:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-time-to-read

kramdown:
  input           : GFM
  auto_ids        : true
  footnote_nr     : 1
  entity_output   : as_char
  toc_levels      : 1..2
  enable_coderay  : false

mathjax           : true

include           : [".htaccess"]
exclude           : ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
keep_files        : ["/images", "favicon.png", ".git"]

# Conversion
incremental       : bool
destination       : ./_site
layouts_dir       : ./_layouts

sitemap:
  changefreq      : daily
  priority        :   0.5


# Site owner
owner:
  name           : Jeruselam
  avatar         : mudur.png
  email          : jeruselam@yandex.com
  disqus-shortname: 
  twitter: 
  facebook: 
  github        : Jeruselam
  stackexchange: 
  linkedin: 
  instagram: 
  flickr: 
  tumblr: 
  pinterest: 
  weibo: 
  google:
    plus: 
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:

#verifications

webmaster_verifications:
  google: t_7kaT-5XWSyzsoUNzXfL3kvx0mmBCEyq-RnnrDbg_s


# Site Info
license_name     : Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License
license_url      : http://creativecommons.org/licenses/by-nc-sa/3.0/

development_mode : true
development_warning: Bu site halen yapım aşamasındadır.  Çok sayıda hata ie karşılaşabilirsiniz. Bulduğunuz hataları github sitesi üzerinden bildirebilirsiniz.

