# Site wide configuration

description       : Türkçe Tercümesi
title             : Kur'an-ı Kerim
logo              : muhur2.png
search            : false
baseurl           : ""
url               : https://jeruselam.github.io
author:
  name            : "Kur'an-ı Kerim - Türkçe Tercümesi"
  url             : https://jeruselam.github.io
  email           : jeruselam@yandex.com
  bio             : "Just another tattooed, time traveling designer."
  picture         : "/images/apple-icon-120x120.png"

# Location

address           : Türkiye
locale            : tr_TR
languages         : ['en', 'tr']
language_default  : 'tr'

# html minify
compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: ["<!-- ", " -->"]
  endings: [p, li, td]
  ignore:
    clippings: [script, css]
    endings: [script, css]
    envs: [local]
  blanklines: false
  startings: [html, head, body]

# Jekyll configuration

enforce_ssl       : jeruselam.github.io
encoding          : UTF-8
safe              : bool
timezone          : Europe/Istanbul
permalink         : /:categories/:title/
markdown          : kramdown
highlighter       : rouge
sass:
  sass_dir        : _sass
  style           : compressed
plugins_dir:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-time-to-read
  - jekyll-assets

assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  cachebust: hard
  js_compressor: uglifier
  css_compressor: sass
  cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true
  assets:
    - "*.png"
    - "bundle.css"
  sources:
    - assets/css
    - images
    - _sass
    - assets/fonts
    - assets/js
  features:
    liquid: false
    integrity: false
    # This will add height and width attributes for an img tag.
    automatic_img_size: true
    # This will add the digest path as an alt attribute for an img tag.
    automatic_img_alt : true


kramdown:
  input           : GFM
  auto_ids        : true
  footnote_nr     : 1
  entity_output   : as_char
  toc_levels      : 1..2
  enable_coderay  : false

mathjax           : true

include           : [".htaccess"]
exclude           : ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
keep_files        : ["/images", "favicon.png", ".git"]

# Conversion
incremental       : bool
destination       : ./_site
layouts_dir       : ./_layouts

sitemap:
  changefreq      : daily
  priority        :   0.5


# Site owner
owner:
  name           : Jeruselam
  avatar         : mudur.png
  email          : jeruselam@yandex.com
  disqus-shortname: 
  twitter: 
  facebook: 
  github        : Jeruselam
  stackexchange: 
  linkedin: 
  instagram: 
  flickr: 
  tumblr: 
  pinterest: 
  weibo: 
  google:
    plus: 
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:

#verifications

webmaster_verifications:
  google: t_7kaT-5XWSyzsoUNzXfL3kvx0mmBCEyq-RnnrDbg_s


# Site Info
licence:
   logo     : cc
   name     : Alıntı-GayriTicari-Türetilemez 4.0 Uluslararası Lisans (CC BY-NC-ND 4.0)
   url      : https://creativecommons.org/licenses/by-nc-nd/4.0/deed.tr
flag: moon


development_mode : true
development_warning: Bu site halen yapım aşamasındadır.  Çok sayıda hata ie karşılaşabilirsiniz. Bulduğunuz hataları bildirebilirsiniz.

